name: "sbom"

permissions:
      actions: read
      contents: write

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: anchore/sbom-action@v0
